services:
    open-actu.url.manager:
        class: OpenActu\UrlBundle\Model\UrlManager
        arguments: [ "@service_container" ]

    open-actu.url_storage.manager:
        class: OpenActu\UrlBundle\Model\UrlStorageManager
        arguments: [ "@service_container" ]

    open-actu.doctrine_listener.url_analyzer:
        class: OpenActu\UrlBundle\DoctrineListener\UrlAnalyzerListener
        arguments:
          - "@service_container"
        tags:
          - { name: doctrine.event_listener, event: postUpdate }
          - { name: doctrine.event_listener, event: postPersist }
