services:
    open-actu.url.manager:
        class: OpenActu\UrlBundle\Model\UrlManager
        arguments: [ "@service_container" ]

    open-actu.url_storage.manager:
        class: OpenActu\UrlBundle\Model\UrlStorageManager
        arguments: [ "@service_container" ]

    open-actu.doctrine_listener.url_analyzer:
        class: OpenActu\UrlBundle\DoctrineListener\UrlAnalyzerListener
        arguments:
          - "@service_container"
        tags:
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: prePersist }

    open-actu.event_listener.url_analyzer:
        class: OpenActu\UrlBundle\EventListener\UrlAnalyzerListener
        arguments:
          - "@open-actu.event_listener.component.url_analyzer"
        tags:
          - { name: kernel.event_listener, event: kernel.controller, method: processReload }
          - { name: kernel.event_listener, event: kernel.controller, method: processAdd }
          - { name: kernel.event_listener, event: kernel.controller, method: processRemove }

    open-actu.event_listener.component.url_analyzer:
        class: OpenActu\UrlBundle\EventListener\Component\UrlAnalyzerComponent
        arguments:
          - "@open-actu.url.manager"
          - "@open-actu.url_storage.manager"
