<?php

namespace OpenActu\UrlBundle\Repository;

/**
 * LinkTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkTestRepository extends \Doctrine\ORM\EntityRepository
{
}
