<?php

namespace OpenActu\UrlBundle\Repository;

/**
 * LinkResponseTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkResponseTestRepository extends \Doctrine\ORM\EntityRepository
{
}
