<?php

namespace OpenActu\UrlBundle\Repository;

/**
 * UrlResponseAnalyzerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlResponseAnalyzerRepository extends \Doctrine\ORM\EntityRepository
{
}
